sudo: false

language: java
jdk:
  - oraclejdk8
  
before_install:
  - mvn dependency:get -DrepoUrl=https://github.com/Valkryst/VRadio.git -Dartifact=com.valkryst.radio:VRadio:1.1
  
script: "mvn cobertura:cobertura"

after_success:
  - bash <(curl -s https://codecov.io/bash)

notification:
  email:
    on_success: never
    on_failure: always
